#print("THIS IS CS50")
#print("Hello")
name = input("Do not yell ").strip().lower()
print(str(name))

#Before You Begin
#Log into code.cs50.io, click on your terminal window, and execute cd by itself. You should find that your terminal window’s prompt resembles the below:


# homework done in :
#https://tatianafortech-symmetrical-succotash-6qwjqrpgqrr24x4w.github.dev/?autoStart=true&folder=%2Fworkspaces%2F111741943&vscodeChannel=stable

# indoor/ $ check50 cs50/problems/2022/python/indoor
# Connecting........
# Authenticating...
# Verifying.......
# Preparing.................
# Uploading...........
# Waiting for results.................................
# Results for cs50/problems/2022/python/indoor generated by check50 v3.3.7
# :) indoor.py exists
# :) input of HELLO yields output of hello
# :) input of THIS IS CS50 yields output of this is cs50
# :) input of 50 yields output of 50
# submit50 cs50/problems/2022/python/indoor
#
#indoor/ $ submit50 cs50/problems/2022/python/indoor
#Connecting........
#Authenticating...
#Verifying.......
#Preparing.................
#Files that will be submitted:
#./indoor.py
#Keeping in mind the course's policy on academic honesty, are you sure you want to submit these files (yes/no)? yes
#Uploading...........
#Go to https://submit.cs50.io/users/Tatianafortech/cs50/problems/2022/python/indoor to see your results.
#indoor/ $