name = input("Speak slowly ").replace(" ", "...")

print(str(name))

#
#playback/ $ python playback.py
#Speak slowly Tas sss ss
#Tas...sss...ss
#playback/ $ python playback.py
#Speak slowly Let's implement a function called hello
#Let's...implement...a...function...called...hello
#playback/ $ check50 cs50/problems/2022/python/playback
#Connecting........
#Authenticating...
#Verifying...........
#Preparing..................
#Uploading............
#Waiting for results..................................
#    Results for cs50/problems/2022/python/playback generated by check50 v3.3.7
#:) playback.py exists
#:) input of "This is CS50" yields output of "This...is...CS50"
#:) input of "This is our week on functions" yields output of "This...is...our...week...on...functions"
#:) input of "Let's implement a function called hello" yields output of "Let's...implement...a...function...called...hello"
#To see the results in your browser go to https://submit.cs50.io/check50/ceb3e679467aac614876017c745ae01b5bac7722

#playback/ $ submit50 cs50/problems/2022/python/playback
#Files that will be submitted:
#./playback.py
#Keeping in mind the course's policy on academic honesty, are you sure you want to submit these files (yes/no)? yes
#Uploading...........
#Go to https://submit.cs50.io/users/Tatianafortech/cs50/problems/2022/python/playback to see your results.
